name: deploy-caderneta-front

on:
  push:
    branches: [ main ]

jobs:
            
    docker:
        name: Docker Hub
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v1
        - name: Publish to Docker Hub
          uses: docker/build-push-action@v1
          with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASS }}
           repository: sirondba/caderneta-front
           tags: ${{github.run_number}}
            
    deploy:
        runs-on: ubuntu-latest
        name: Deploy Heroku
        needs: docker
        steps:
        - uses: actions/checkout@v2
        - name: Deploy to Heroku
          uses: AkhileshNS/heroku-deploy@v3.8.8
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            heroku_app_name: ${{secrets.HEROKU_APP}}
            
    #notifySlack:
    #    name: Notify slack
    #    runs-on: ubuntu-latest
    #    needs: [deploy]
    #    steps:
    #    - uses: actions/checkout@v2
    #    - name: Notify Slack
    #      uses: drilonrecica/action-slack-notify@0.0.3
    #      env:
    #        SLACK_TITLE: Notify Deploy
    #        SLACK_ICON: https://github.com/rtCamp.png?size=48
    #        SLACK_MESSAGE: 'A Aplicação caderneta-front:v${{github.run_number}}, já estar disponivel no ambiente de produção'            
    #        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

